name: dev.to
on:
  schedule:
    - cron: "0 0 * * sun"

jobs:
  steps:
    name: Fetch posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: khaosdoctor/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/lexplt"
